'use client'

import { useState } from 'react'

export default function Recommendations({ name, recommendations, messages, onRestart }) {
  const [saved, setSaved] = useState(false)
  const [pdfGenerating, setPdfGenerating] = useState(false)

  function buildProfile() {
    return {
      name,
      date: new Date().toISOString().slice(0, 10),
      recommendations,
      conversationSummary: messages
        .filter((m) => m.role === 'user')
        .map((m) => m.content)
        .join('\n\n'),
    }
  }

  function saveProfile() {
    const profile = buildProfile()
    const blob = new Blob([JSON.stringify(profile, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `biz-profile-${name.toLowerCase().replace(/\s+/g, '-')}-${profile.date}.json`
    a.click()
    URL.revokeObjectURL(url)
    setSaved(true)
  }

  async function downloadPDF() {
    setPdfGenerating(true)
    try {
      const { jsPDF } = await import('jspdf')
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

      const pageW = doc.internal.pageSize.getWidth()
      const margin = 20
      const contentW = pageW - margin * 2
      let y = margin

      function addText(text, opts = {}) {
        const { fontSize = 11, bold = false, color = [30, 30, 30], indent = 0 } = opts
        doc.setFontSize(fontSize)
        doc.setFont('helvetica', bold ? 'bold' : 'normal')
        doc.setTextColor(...color)
        const lines = doc.splitTextToSize(text, contentW - indent)
        for (const line of lines) {
          if (y > 270) {
            doc.addPage()
            y = margin
          }
          doc.text(line, margin + indent, y)
          y += fontSize * 0.45
        }
        return y
      }

      function addGap(mm = 5) {
        y += mm
      }

      // Title
      addText('Business Recommendations', { fontSize: 22, bold: true, color: [80, 60, 200] })
      addGap(3)
      addText(`For ${name} · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, {
        fontSize: 11,
        color: [120, 120, 120],
      })
      addGap(8)

      // Divider
      doc.setDrawColor(200, 200, 200)
      doc.line(margin, y, pageW - margin, y)
      addGap(8)

      recommendations.forEach((rec, i) => {
        addText(`${i + 1}. ${rec.title}`, { fontSize: 15, bold: true })
        addGap(3)

        addText('Why this for you:', { fontSize: 10, bold: true, color: [100, 100, 100] })
        addGap(2)
        addText(rec.why, { fontSize: 11, indent: 4 })
        addGap(4)

        addText('First steps:', { fontSize: 10, bold: true, color: [100, 100, 100] })
        addGap(2)
        rec.steps.forEach((step, si) => {
          addText(`${si + 1}. ${step}`, { fontSize: 11, indent: 4 })
          addGap(1)
        })

        addGap(8)
        if (i < recommendations.length - 1) {
          doc.setDrawColor(230, 230, 230)
          doc.line(margin, y, pageW - margin, y)
          addGap(8)
        }
      })

      addGap(4)
      addText('Generated by Biz For You', { fontSize: 9, color: [160, 160, 160] })

      doc.save(`biz-recommendations-${name.toLowerCase().replace(/\s+/g, '-')}.pdf`)
    } catch (err) {
      console.error('PDF generation failed:', err)
      alert('PDF generation failed. Please try again.')
    }
    setPdfGenerating(false)
  }

  return (
    <div style={{ minHeight: '100vh', padding: '40px 20px' }}>
      <div style={{ maxWidth: '720px', margin: '0 auto' }}>
        {/* Header */}
        <div style={{ marginBottom: '40px' }}>
          <div
            style={{
              display: 'inline-block',
              fontSize: '12px',
              fontWeight: '600',
              textTransform: 'uppercase',
              letterSpacing: '1px',
              color: 'var(--accent)',
              marginBottom: '12px',
            }}
          >
            Your results
          </div>
          <h1
            style={{
              fontSize: '28px',
              fontWeight: '700',
              letterSpacing: '-0.5px',
              marginBottom: '8px',
            }}
          >
            {name}, here are your opportunities
          </h1>
          <p style={{ color: 'var(--text-muted)', fontSize: '15px' }}>
            Based on your unique situation, skills, and unfair advantages.
          </p>
        </div>

        {/* Recommendations */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', marginBottom: '40px' }}>
          {recommendations.map((rec, i) => (
            <div
              key={i}
              style={{
                background: 'var(--bg-card)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--radius)',
                overflow: 'hidden',
              }}
            >
              {/* Card header */}
              <div
                style={{
                  padding: '20px 24px 16px',
                  borderBottom: '1px solid var(--border)',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px',
                }}
              >
                <div
                  style={{
                    width: '28px',
                    height: '28px',
                    borderRadius: '8px',
                    background: 'var(--accent-dim)',
                    border: '1px solid var(--accent)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '13px',
                    fontWeight: '700',
                    color: 'var(--accent)',
                    flexShrink: 0,
                  }}
                >
                  {i + 1}
                </div>
                <h2 style={{ fontSize: '17px', fontWeight: '700', margin: 0 }}>{rec.title}</h2>
              </div>

              {/* Card body */}
              <div style={{ padding: '20px 24px' }}>
                <div style={{ marginBottom: '20px' }}>
                  <div
                    style={{
                      fontSize: '11px',
                      fontWeight: '700',
                      textTransform: 'uppercase',
                      letterSpacing: '0.8px',
                      color: 'var(--accent)',
                      marginBottom: '8px',
                    }}
                  >
                    Why this for you
                  </div>
                  <p style={{ fontSize: '14px', lineHeight: '1.7', color: 'var(--text)', margin: 0 }}>
                    {rec.why}
                  </p>
                </div>

                <div>
                  <div
                    style={{
                      fontSize: '11px',
                      fontWeight: '700',
                      textTransform: 'uppercase',
                      letterSpacing: '0.8px',
                      color: 'var(--text-muted)',
                      marginBottom: '10px',
                    }}
                  >
                    First steps
                  </div>
                  <ol style={{ margin: 0, padding: 0, listStyle: 'none' }}>
                    {rec.steps.map((step, si) => (
                      <li
                        key={si}
                        style={{
                          display: 'flex',
                          gap: '10px',
                          marginBottom: '8px',
                          fontSize: '14px',
                          lineHeight: '1.6',
                        }}
                      >
                        <span
                          style={{
                            flexShrink: 0,
                            width: '20px',
                            height: '20px',
                            borderRadius: '50%',
                            background: 'var(--bg)',
                            border: '1px solid var(--border)',
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            fontSize: '11px',
                            fontWeight: '600',
                            color: 'var(--text-muted)',
                            marginTop: '2px',
                          }}
                        >
                          {si + 1}
                        </span>
                        <span>{step}</span>
                      </li>
                    ))}
                  </ol>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Actions */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '12px',
            marginBottom: '40px',
          }}
        >
          <button
            onClick={downloadPDF}
            disabled={pdfGenerating}
            style={{
              padding: '13px 24px',
              background: 'var(--accent)',
              color: '#fff',
              border: 'none',
              borderRadius: 'var(--radius-sm)',
              fontSize: '15px',
              fontWeight: '600',
              cursor: pdfGenerating ? 'wait' : 'pointer',
              opacity: pdfGenerating ? 0.7 : 1,
              transition: 'background 0.2s',
            }}
            onMouseEnter={(e) => { if (!pdfGenerating) e.target.style.background = 'var(--accent-hover)' }}
            onMouseLeave={(e) => { if (!pdfGenerating) e.target.style.background = 'var(--accent)' }}
          >
            {pdfGenerating ? 'Generating PDF...' : '↓ Download as PDF'}
          </button>

          <button
            onClick={saveProfile}
            style={{
              padding: '13px 24px',
              background: saved ? 'var(--bg-card)' : 'var(--bg-input)',
              color: saved ? 'var(--success)' : 'var(--text)',
              border: `1px solid ${saved ? 'var(--success)' : 'var(--border)'}`,
              borderRadius: 'var(--radius-sm)',
              fontSize: '15px',
              fontWeight: '600',
              cursor: 'pointer',
              transition: 'all 0.2s',
            }}
          >
            {saved ? '✓ Profile saved' : '↓ Save profile (for next year)'}
          </button>

          <button
            onClick={onRestart}
            style={{
              padding: '13px 24px',
              background: 'transparent',
              color: 'var(--text-muted)',
              border: '1px solid var(--border)',
              borderRadius: 'var(--radius-sm)',
              fontSize: '15px',
              fontWeight: '500',
              cursor: 'pointer',
              transition: 'color 0.2s',
            }}
            onMouseEnter={(e) => (e.target.style.color = 'var(--text)')}
            onMouseLeave={(e) => (e.target.style.color = 'var(--text-muted)')}
          >
            Start over
          </button>
        </div>

        <p style={{ fontSize: '13px', color: 'var(--text-muted)', lineHeight: '1.6' }}>
          <strong style={{ color: 'var(--text)' }}>Save your profile</strong> to upload next
          year for a faster, updated assessment as your situation evolves.
        </p>
      </div>
    </div>
  )
}
